version: "3"
services:
  db:
    image: "postgres:9.6.5"
    restart: always
    command: bash -c "apt-get update -y && apt-get install wget -y 
    
    && cd /tmp/ && wget https://data.london.gov.uk/download/google-mobility-by-borough/26d5821b-fcb6-4aae-af73-ee0596942d16/google_activity_by_London_Borough.csv"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
      - .:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  #nginx:
   # image: nginx
    #command: bash -c "apt-get install wget -y && cd /opt/mytask/ && wget https://data.london.gov.uk/download/google-mobility-by-borough/26d5821b-fcb6-4aae-af73-ee0596942d16/google_activity_by_London_Borough.csv"
    #volumes:
     # - "dbdata:/var/lib/myData"

volumes:
  dbdata:
